apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc  # Removed 'labels' from here

spec:
  replicas: 3
  selector:
   app: myapp

  template: 
    metadata: 
      labels:
        app: myapp  # Labels should be inside template.metadata
        type: front-end

    spec: 
      containers:
      - name: nginx-container
        image: nginx
